name=input("Enter your Name")
age=input("Enter your age")
gender=input("Enter your Gender")
mobile=input("Enter your Mobile Number")
college=input("Enter your College Name")

print("\n=====================ID CARD======================")
print("Name :" ,name)
print("Age:", age)
print("Gender:",gender)
print("Mobile", mobile)
print("College:",college)
print("\n==================================================")

print("\n=======================MEMORY DETAILS=============")
print("Name = ",id(name))
print("Age = ",id(age))
print("Gender = ",id(gender))
print("Mobile = ",id(mobile))
print("College = ",id(college))